import{a as u,S as d,i as f}from"./assets/vendor-frHSA4Lh.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();u.defaults.baseURL="https://pixabay.com/api/";async function p(o,s){try{return(await u.get("",{params:{per_page:15,page:s,key:"50295834-c918df4fa87d72bde5e1e5104",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data.hits}catch(r){throw console.log(r,response.status),r}}const m=new d(".gallery a",{captionsData:"alt",captionDelay:250}),y=document.querySelector(".gallery");function g(o){const s=o;console.log(o).map(r=>{const e=["likes","views","comments","downloads"].map(t=>`<p class="info-item">${h(t)}:<span class="info">${r[t]}</span></p>`).join("");return`<li class="image-item">
    <a href="${r.largeImageURL}" title="${r.tags}">
    <img src="${r.webformatURL}" 
    alt="${r.tags}"
    />
    </a>
    <div class="gallery-info">
    ${e}
    </div>
    </li>`}).join(""),y.insertAdjacentHTML("beforeend",s),m.refresh()}function h(o){return o&&o.charAt(0).toUpperCase()+o.slice(1).toLowerCase()}const L=document.querySelector(".form"),i=document.querySelector('input[name="search-text"]'),l=document.querySelector('button[type="submit"]');document.querySelector(".gallery");document.addEventListener("DOMContentLoaded",()=>{c()});L.addEventListener("submit",async o=>{if(o.preventDefault(),c()){const s=await p(i.value.trim());console.log(s);try{g(s)}catch(r){console.log("new error in main:",r)}}else return f.error({title:"Поле не може бути порожнім",message:"Будь ласка, введіть текст для пошуку.",position:"topRight",timeout:2e3})});i.addEventListener("input",c);function c(){return i.value.trim()!==""?(l.disabled=!1,!0):(l.disabled=!0,!1)}
//# sourceMappingURL=index.js.map
