import{a as b,S as B,i}from"./assets/vendor-frHSA4Lh.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const y of r.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&a(y)}).observe(document,{childList:!0,subtree:!0});function t(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(o){if(o.ep)return;o.ep=!0;const r=t(o);fetch(o.href,r)}})();b.defaults.baseURL="https://pixabay.com/api/";async function S(e,n=1){try{return(await b.get("",{params:{per_page:15,page:n,key:"50295834-c918df4fa87d72bde5e1e5104",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(t){throw console.error("API Error:",t),t}}const w=document.querySelector(".gallery"),d=document.querySelector(".loader"),f=document.querySelector(".loadMoreBtn"),R=new B(".gallery a",{captionsData:"alt",captionDelay:250});function v(e){const n=e.map(t=>{const o=["likes","views","comments","downloads"].map(r=>`<p class="info-item">${C(r)}:<span class="info">${t[r]}</span></p>`).join("");return`<li class="image-item">
    <a href="${t.largeImageURL}" title="${t.tags}">
    <img src="${t.webformatURL}" 
    alt="${t.tags}"
    />
    </a>
    <div class="gallery-info">
    ${o}
    </div>
    </li>`}).join("");w.insertAdjacentHTML("beforeend",n),R.refresh()}function C(e){return e&&e.charAt(0).toUpperCase()+e.slice(1).toLowerCase()}function g(){w.innerHTML=""}function M(){d&&(d.style.display="inline-block")}function m(){d&&(d.style.display="none")}function D(){f&&(f.style.display="inline-block")}function s(){f&&(f.style.display="none")}const E=document.querySelector(".form"),h=document.querySelector('input[name="search-text"]'),L=document.querySelector('button[type="submit"]'),P=document.querySelector(".gallery"),$=document.querySelector(".loadMoreBtn"),O=15;let l=0,c=1,u="";document.addEventListener("DOMContentLoaded",()=>{p(),s(),m()});h.addEventListener("input",p);E.addEventListener("submit",async e=>{e.preventDefault();const n=h.value.trim();if(n!==u&&(c=1,l=0,g(),s()),u=n,!p()){i.error({title:"Поле не може бути порожнім",message:"Будь ласка, введіть текст для пошуку.",position:"topRight"}),s();return}M();try{const t=await S(u,c),a=t.hits;l=t.totalHits,a.length===0?(i.info({title:"Відхилено",message:"За Вашим запитом зображень не знайдено.",position:"topRight"}),s()):(v(a),q())}catch{i.error({title:"Помилка",message:"Під час завантаження зображень сталася помилка. Спробуйте ще раз.",position:"topRight"}),g(),s()}finally{m(),p()}});function p(){return h.value.trim()!==""?(L.disabled=!1,!0):(L.disabled=!0,!1)}$.addEventListener("click",async()=>{c++,M(),s();try{const n=(await S(u,c)).hits;v(n),q(),H()}catch(e){console.error("Помилка під час завантаження додаткових зображень:",e),i.error({title:"Помилка",message:"Під час завантаження додаткових зображень сталася помилка. Спробуйте ще раз.",position:"topRight"}),s()}finally{m()}});function q(){const e=Math.ceil(l/O);c>=e||l===0?(s(),l>0&&i.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"})):D()}function H(){const e=P.firstElementChild;if(console.log("Gallery Card Element:",e),e){const t=e.getBoundingClientRect().height;console.log("Card Height:",t),console.log("Attempting to scroll by:",t*2),window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
